services:
  frontend:
    image: ghcr.io/iboqvist/tomo-web/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: ghcr.io/iboqvist/tomo-web/backend:latest
    environment:
      DATABASE_URL: postgresql://tomo:tomo@db/tomo
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:18
    environment:
      POSTGRES_USER: tomo
      POSTGRES_PASSWORD: tomo
      POSTGRES_DB: tomo
    volumes:
      - pgdata:/var/lib/postgresql
    restart: unless-stopped

volumes:
  pgdata:
